In [20]:
import numpy as np                        
np.random.seed(1)
input_nodes = 5                             # nombre de neurones dans chaque couche
hidden_1_nodes =3
hidden_2_nodes = 5
output_nodes = 4

In [21]:
x = np.random.randint(1, 100, size = (input_nodes, 1)) / 100
print('x')                                  # Entrées
print(x, x.shape)
y = np.random.randint(1, 100, size = (output_nodes, 1)) / 100
print('y')                                  # Cibles
print(y, y.shape)

x
[[0.38]
 [0.13]
 [0.73]] (3, 1)
y
[[0.1 ]
 [0.76]] (2, 1)


In [22]:
def relu(x, leak = 0):                      # ReLU
    return np.where(x <= 0, leak * x, x)
def sig(x):                                 # Sigmoide
    return 1/(1 + np.exp(-x))
def mse(y_true, y_pred):                    # MSE
    return np.mean((y_true - y_pred)**2)

In [23]:
w1 = np.random.random(size = (hidden_1_nodes, input_nodes))
b1 = np.zeros(shape = (hidden_1_nodes, 1))
np.set_printoptions(2)
print(w1, w1.shape)
print('w1')                               
print(w1, w1.shape)
print('\n')
print('b1')                               
print(b1, b1.shape)
w2 = np.random.random(size = (hidden_2_nodes, hidden_1_nodes))
b2 = np.zeros(shape = (hidden_2_nodes, 1))
print('w2')                                
print(w2, w2.shape)
print('\n')
print('b2')                               
print(b2, b2.shape)
w3 = np.random.random(size = (output_nodes, hidden_2_nodes))
b3 = np.zeros(shape = (output_nodes, 1))
print('w3')                                 
print(w3, w3.shape)
print('\n')
print('b3')                                
print(b3, b3.shape)


[[1.   0.24 0.4 ]
 [0.39 0.67 0.94]] (2, 3)
w1
[[1.   0.24 0.4 ]
 [0.39 0.67 0.94]] (2, 3)


b1
[[0.]
 [0.]] (2, 1)
w2
[[0.85 0.31]
 [0.52 0.44]] (2, 2)


b2
[[0.]
 [0.]] (2, 1)
w3
[[0.23 0.53]
 [0.91 0.46]] (2, 2)


b3
[[0.]
 [0.]] (2, 1)


In [24]:
in_hidden_1 = w1.dot(x) + b1
print('in_hidden_1')
print(in_hidden_1, in_hidden_1.shape)

in_hidden_1
[[0.7 ]
 [0.92]] (2, 1)


In [25]:
out_hidden_1 = relu(in_hidden_1, leak = 0.1)
print('out_hidden_1')
print(out_hidden_1, out_hidden_1.shape)

out_hidden_1
[[0.7 ]
 [0.92]] (2, 1)


In [26]:
in_hidden_2 = w2.dot(out_hidden_1) + b2
print('in_hidden_2')
print(in_hidden_2, in_hidden_2.shape)

in_hidden_2
[[0.88]
 [0.77]] (2, 1)


In [27]:
out_hidden_2 = relu(in_hidden_2, leak = 0.1)
print('out_hidden_2')
print(out_hidden_2, out_hidden_2.shape)

out_hidden_2
[[0.88]
 [0.77]] (2, 1)


In [28]:
in_output_layer = w3.dot(out_hidden_2) + b3
print('in_output_layer')
print(in_output_layer, in_output_layer.shape)

in_output_layer
[[0.62]
 [1.16]] (2, 1)


In [29]:
out_hidden_2 = sig(in_hidden_2)
print('out_hidden_2')
print(out_hidden_2, out_hidden_2.shape)

out_hidden_2
[[0.71]
 [0.68]] (2, 1)


In [30]:
in_output_layer = w3.dot(out_hidden_2) + b3
print('in_output_layer')
print(in_output_layer, in_output_layer.shape)

in_output_layer
[[0.53]
 [0.96]] (2, 1)


In [31]:
y_hat = sig(in_output_layer)
print('y_hat')
print(y_hat, y_hat.shape)

y_hat
[[0.63]
 [0.72]] (2, 1)


In [32]:
print('y')
print(y, y.shape)

y
[[0.1 ]
 [0.76]] (2, 1)


In [33]:
mse(y, y_hat)

0.14061675468127363